### ISSUE TITLE
emulated IE9 errors in useragent module

### ISSUE THREAD

**Issue by Firzenizer** [diversen/coscms#1]
Getting following errors with IE11 emulated IE9.

User agent: 'Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko'

Getting this return:
  'platform' => string 'Windows' (length=7)
  'browser' => null
  'version' => null

A PHP Error was encountered

Severity: Notice
Message: Undefined offset: 0
Filename: coslib/Useragent.php
Line Number: 78

A PHP Error was encountered

Severity: Notice
Message: Undefined offset: 0
Filename: coslib/Useragent.php
Line Number: 79

A PHP Error was encountered

Severity: Notice
Message: Undefined offset: 0
Filename: coslib/Useragent.php
Line Number: 94

A PHP Error was encountered

Severity: Notice
Message: Undefined offset: 0
Filename: coslib/Useragent.php
Line Number: 111

**Comment by diversen** [comment]
I am afraid I don't not have the time for the moment, but I will return to it some day. Just surprise the errors for a quick solution. Let me know if you fix this issue, then give me a signal .)

**Comment by diversen** [comment]
Well I had to look into the issue. I will replace my useragent lib with this lib: https://github.com/donatj/PhpUserAgent This is also where I found the useragent function. Test this lib and I would think the issue has been fixed .)

**Comment by diversen** [comment]
closed long time ago ...
